### ISSUE TITLE
How to Use QueryProperties with MVVM ViewModels

### ISSUE THREAD

**Issue by jminnihan** [jamesmontemagno/app-xf-shell-navigation#1]
A page example that sends and receives a QueryParameter value using MVVM ViewModels would be a good additional example to show both here and in your corresponding blog post.

For example, how do you reference these QueryParameters from within a ViewModel? Also, can we wait for them when awaiting the return of the Shell.Current.GoToAsync() with the Shell.PresentationMode="ModalAnimated"?

**Comment by jamesmontemagno** [comment]
You can add them directly onto your view model. XF Shell will pass them down to your Binding Context automatically :)
